xml.food do
  # general info
  xml.common_name(food.common_name)
  xml.manufacturer_name(food.manufacturer_name)
  xml.scientific_name(food.scientific_name)
  xml.category(food.category)
  xml.short_description(food.short_description)
  xml.long_description(food.long_description)
  xml.refuse_description(food.refuse_description)
  xml.density(food.density)
  # macronutrients
  xml.energy(food.energy, unit: UNIT_FOR[:energy])
  xml.water(food.water, unit: UNIT_FOR[:water])
  xml.protein(food.protein, unit: UNIT_FOR[:protein])
  xml.carbohydrate(food.carbohydrate, unit: UNIT_FOR[:carbohydrate])
  xml.fat(food.fat, unit: UNIT_FOR[:fibers])
  xml.fibers(food.fibers, unit: UNIT_FOR[:fibers])
  xml.sugar(food.sugar, unit: UNIT_FOR[:sugar])
  xml.alcohol(food.alcohol, unit: UNIT_FOR[:alcohol])
  xml.caffeine(food.caffeine, unit: UNIT_FOR[:caffeine])
  # fatty acids, fat micronutrients
  xml.saturated_fat(food.saturated_fat, unit: UNIT_FOR[:saturated_fat])
  xml.monounsaturated_fat(food.monounsaturated_fat, unit: UNIT_FOR[:monounsatured_fat])
  xml.polyunsaturated_fat(food.polyunsaturated_fat, unit: UNIT_FOR[:polyunsaturated_fat])
  xml.trans_fat(food.trans_fat, unit: UNIT_FOR[:trans_fat])
  xml.omega_3(food.omega_3, unit: UNIT_FOR[:omega_3])
  xml.epa(food.epa, unit: UNIT_FOR[:epa])
  xml.dpa(food.dpa, unit: UNIT_FOR[:dpa])
  xml.dha(food.dha, unit: UNIT_FOR[:dha])
  xml.ala(food.ala, unit: UNIT_FOR[:ala])
  xml.omega_6(food.omega_6, unit: UNIT_FOR[:omega_6])
  xml.cholesterol(food.cholesterol, unit: UNIT_FOR[:cholesterol])
  # minerals
  xml.calcium(food.calcium, unit: UNIT_FOR[:calcium])
  xml.iron(food.iron, unit: UNIT_FOR[:iron])
  xml.magnesium(food.magnesium, unit: UNIT_FOR[:magnesium])
  xml.phosphorus(food.phosphorus, unit: UNIT_FOR[:phosphorus])
  xml.potassium(food.potassium, unit: UNIT_FOR[:potassium])
  xml.sodium(food.sodium, unit: UNIT_FOR[:sodium])
  xml.zinc(food.zinc, unit: UNIT_FOR[:zinc])
  xml.copper(food.copper, unit: UNIT_FOR[:copper])
  xml.manganese(food.manganese, unit: UNIT_FOR[:manganese])
  xml.selenium(food.selenium, unit: UNIT_FOR[:selenium])
  xml.fluoride(food.fluoride, unit: UNIT_FOR[:fluoride])
  # vitamins
  xml.vit_a(food.vit_a, unit: UNIT_FOR[:vit_a])
  xml.vit_b1(food.vit_b1, unit: UNIT_FOR[:vit_b1])
  xml.vit_b2(food.vit_b2, unit: UNIT_FOR[:vit_b2])
  xml.vit_b3(food.vit_b3, unit: UNIT_FOR[:vit_b3])
  xml.vit_b5(food.vit_b5, unit: UNIT_FOR[:vit_b5])
  xml.vit_b6(food.vit_b6, unit: UNIT_FOR[:vit_b6])
  xml.vit_b7(food.vit_b7, unit: UNIT_FOR[:vit_b7])
  xml.vit_b9(food.vit_b9, unit: UNIT_FOR[:vit_b9])
  xml.vit_b12(food.vit_b12, unit: UNIT_FOR[:vit_b12])
  xml.vit_C(food.vit_c, unit: UNIT_FOR[:vit_c])
  xml.vit_D(food.vit_d, unit: UNIT_FOR[:vit_d])
  xml.vit_E(food.vit_e, unit: UNIT_FOR[:vit_e])
  xml.vit_K(food.vit_k, unit: UNIT_FOR[:vit_k])
  xml.alpha_carotene(food.alpha_carotene, unit: UNIT_FOR[:alpha_carotene])
  xml.beta_carotene(food.beta_carotene, unit: UNIT_FOR[:beta_carotene])
  # reference
  xml.source(food.source)
end
